# Generated by Django 4.1.5 on 2023-01-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agaDarkApps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_diagosis_history',
            name='dietary_report_recieved_status',
            field=models.BooleanField(default=False),
        ),
    ]
