# Generated by Django 3.2.4 on 2023-01-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agaDarkApps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_history',
            name='case_number',
            field=models.CharField(default='', max_length=120),
        ),
    ]
