# Generated by Django 3.2.4 on 2023-02-14 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agaDarkApps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='medical_history_diagnosis_payment',
            name='dietary_reference_code',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AddField(
            model_name='patient_laboratory',
            name='discount_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='patient_laboratory',
            name='discount_state',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Discount_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0.0)),
                ('date_updated', models.DateField()),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
