# Generated by Django 3.2.4 on 2023-01-25 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agaDarkApps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_History_Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_total_cost', models.FloatField(default=0.0)),
                ('supplement_total_cost', models.FloatField(default=0.0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('amount_paid', models.FloatField(default=0.0)),
                ('recepit', models.CharField(default='', max_length=120)),
                ('date_paid', models.DateField()),
                ('patient_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agaDarkApps.patient_history')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient_laboratory_dietary_payment',
            name='lab_supplement',
        ),
        migrations.DeleteModel(
            name='Patient_Laboratory_Dietary_Cost',
        ),
        migrations.DeleteModel(
            name='Patient_Laboratory_Dietary_Payment',
        ),
    ]
