# Generated by Django 3.2.4 on 2022-12-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agaDarkApps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_diagosis_history',
            name='date_diagosed',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient_history',
            name='checked_in_date_time',
            field=models.DateField(default='1982-01-02'),
        ),
        migrations.AlterField(
            model_name='patient_history',
            name='checked_out_date_time',
            field=models.DateField(default='1982-01-02'),
        ),
    ]
