# Generated by Django 4.1.5 on 2023-02-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agaDarkApps', '0002_discount_discount_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Discount_History',
        ),
    ]
