# Generated by Django 3.2.4 on 2023-01-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agaDarkApps', '0002_patient_history_case_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='waiting_state',
            field=models.CharField(default='checked out', max_length=120),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registration_number',
            field=models.CharField(default='', max_length=150),
        ),
    ]
