# Generated by Django 4.1.5 on 2023-01-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agaDarkApps', '0002_patient_diagosis_history_dietary_report_recieved_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_dietary_details',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
