# Generated by Django 3.2.4 on 2023-01-25 08:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agaDarkApps', '0002_auto_20230125_0833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medical_History_Diagnosis',
            new_name='Medical_History_Diagnosis_Payment',
        ),
    ]
