# Generated by Django 3.2.4 on 2022-12-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agaDarkApps', '0002_auto_20221201_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietary_supplementary',
            name='quanity',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='patient_laboratory',
            name='date_reported',
            field=models.DateField(),
        ),
    ]
