# Generated by Django 3.2.4 on 2023-01-23 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agaDarkApps', '0003_patient_dietary_details_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPD_Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_time_charge', models.FloatField(default=0.0)),
                ('second_time_charge', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='OPD_Payment_Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField(default=0.0)),
                ('recepit', models.CharField(max_length=120)),
                ('patient_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agaDarkApps.patient_history')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OPD_Charges_Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_time_old_charge', models.FloatField(default=0.0)),
                ('second_time_old_charge', models.FloatField(default=0.0)),
                ('date_edited', models.DateField()),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
