# Generated by Django 3.2.4 on 2022-12-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agaDarkApps', '0003_auto_20221215_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_dietary_details',
            name='quanity',
            field=models.IntegerField(default=0),
        ),
    ]
