# Generated by Django 3.2.4 on 2022-12-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agaDarkApps', '0004_patient_dietary_details_quanity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietary_supplementary',
            old_name='quanity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='patient_dietary_details',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
