# Generated by Django 4.1.5 on 2023-02-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agaDarkApps', '0004_discount_patient_laboratory_discount_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_laboratory',
            name='discount_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
