# Generated by Django 4.1.5 on 2023-02-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agaDarkApps', '0005_patient_laboratory_discount_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_history_diagnosis_payment',
            name='dietary_reference_code',
            field=models.CharField(default=' ', max_length=120),
        ),
    ]
