# Generated by Django 3.2.4 on 2023-01-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agaDarkApps', '0006_hospital_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_staff',
            name='telephone',
            field=models.CharField(default=' ', max_length=170),
        ),
    ]
