# Generated by Django 3.2.4 on 2023-01-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agaDarkApps', '0007_hospital_staff_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietary_supplementary',
            name='photo',
            field=models.FileField(default=' ', upload_to='uploads'),
        ),
    ]
